version: '3.8'

services:
  app:
    image: php:8.3.14-fpm
    container_name: yii-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - yii-network

  web:
    image: nginx:latest
    container_name: yii-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fastcgi_params:/etc/nginx/conf.d/fastcgi_params
    depends_on:
      - app
    networks:
      - yii-network

  db:
    image: postgres:latest
    container_name: yii-db
    environment:
      POSTGRES_DB: pet-project
      POSTGRES_USER: u1
      POSTGRES_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - yii-network

volumes:
  db_data:

networks:
  yii-network:
    driver: bridge